const PDFDocument = require('pdfkit');

/**
 * Generic, reusable PDF-building helpers shared by both the donation
 * receipt and the donation certificate (see receiptService.js — added in
 * a later step — for the documents actually built with these).
 *
 * Deliberately model-agnostic: this file has no idea whether it's being
 * asked to render something for a Transaction (financial donation) or a
 * completed Donation (physical donation). It only ever receives plain
 * data objects, so both flows (see the updated business logic — financial
 * donations get a receipt+certificate automatically on payment; physical
 * donations get a certificate only once an admin marks the inquiry
 * 'Completed') can reuse it identically.
 */

const BRAND = {
  forest: '#0F4C2A',
  forestDark: '#0A3820',
  saffron: '#F97316',
  ivory: '#FAFAF7',
  text: '#1E293B',
  muted: '#6B7280',
};

const ORG_NAME = 'Ek Nai Pehal';
const ORG_TAGLINE = 'School of New Hopes';

const PAGE_MARGIN = 50;

/**
 * Create a new PDF document with sensible, shared defaults.
 * Callers get the raw pdfkit document back and draw their own body
 * content between calling this and calling drawFooter/finalize.
 */
const createDocument = ({ size = 'A4', layout = 'portrait' } = {}) => {
  return new PDFDocument({
    size,
    layout,
    margin: PAGE_MARGIN,
    info: {
      Author: ORG_NAME,
      Creator: ORG_NAME,
    },
  });
};

/**
 * Draw the shared letterhead-style header used at the top of every
 * generated document (receipt and certificate alike). Returns the Y
 * position immediately below the header, so callers know where to start
 * their own content without hardcoding a magic offset.
 */
const drawHeader = (doc, { subtitle } = {}) => {
  const startY = doc.y;

  doc
    .rect(0, 0, doc.page.width, 90)
    .fill(BRAND.forest);

  doc
    .fillColor('#FFFFFF')
    .fontSize(22)
    .font('Helvetica-Bold')
    .text(ORG_NAME, PAGE_MARGIN, 28, { continued: false });

  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor(BRAND.ivory)
    .text(ORG_TAGLINE, PAGE_MARGIN, 56);

  if (subtitle) {
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .fillColor('#FFFFFF')
      .text(subtitle, PAGE_MARGIN, 0, {
        width: doc.page.width - PAGE_MARGIN * 2,
        align: 'right',
      });
  }

  doc.fillColor(BRAND.text);
  doc.y = 90 + 30;
  doc.x = PAGE_MARGIN;

  return doc.y;
};

/**
 * Draw a thin, muted footer near the bottom of the current page —
 * generation timestamp and a disclaimer. Call once per document, after
 * all body content, right before doc.end().
 */
const drawFooter = (doc, { note } = {}) => {
  const footerY = doc.page.height - PAGE_MARGIN - 40;

  doc
    .moveTo(PAGE_MARGIN, footerY)
    .lineTo(doc.page.width - PAGE_MARGIN, footerY)
    .strokeColor('#E5E7EB')
    .lineWidth(1)
    .stroke();

  doc
    .fontSize(8)
    .font('Helvetica')
    .fillColor(BRAND.muted)
    .text(
      note || `Generated by ${ORG_NAME} on ${new Date().toUTCString()}`,
      PAGE_MARGIN,
      footerY + 10,
      { width: doc.page.width - PAGE_MARGIN * 2, align: 'center' }
    );
};

/**
 * A labeled value row (e.g. "Receipt Number:  ENP-20260716-000001"), used
 * repeatedly by both the receipt and certificate layouts to keep spacing
 * and typography consistent without each caller re-implementing it.
 */
const drawField = (doc, label, value, { gap = 18 } = {}) => {
  const labelWidth = 160;

  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(BRAND.muted)
    .text(label, PAGE_MARGIN, doc.y, { continued: true, width: labelWidth });

  doc
    .font('Helvetica')
    .fillColor(BRAND.text)
    .text(`  ${value}`);

  doc.moveDown(gap / 18);
};

/**
 * Stream a finished (but not yet `.end()`-ed) pdfkit document straight to
 * an Express response as a downloadable/inline PDF, then finalize it.
 * Centralizing this means every PDF endpoint sets identical, correct
 * headers rather than each controller re-deriving them.
 */
const streamPdfToResponse = (doc, res, { filename, disposition = 'attachment' }) => {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `${disposition}; filename="${filename}"`);

  doc.pipe(res);
  doc.end();
};

module.exports = {
  BRAND,
  ORG_NAME,
  ORG_TAGLINE,
  PAGE_MARGIN,
  createDocument,
  drawHeader,
  drawFooter,
  drawField,
  streamPdfToResponse,
};